import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/components/Providers/theme-provider";
import { cn } from "@/libs/utils";
import React from "react";

const rowdies = localFont({
  src: "../libs/fonts/Rowdies-Bold.ttf",
  variable: "--font-rowdies",
});
const roboto = localFont({
  src: "../libs/fonts/Roboto.ttf",
  variable: "--font-roboto",
});
const kobe = localFont({
  src: "../libs/fonts/kobe.otf",
  variable: "--font-kobe",
});
const wenkaitc = localFont({
  src: "../libs/fonts/WenKaiTC.ttf",
  variable: "--font-wenkai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sideBar,
}: Readonly<{
  children: React.ReactNode;
  sideBar: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        className={cn(
          "bg-background text-text min-h-screen w-screen overflow-x-hidden lg:grid lg:grid-cols-[1fr_6rem] xl:grid-cols-[1fr_8rem]",
          rowdies.variable,
          roboto.variable,
          kobe.variable,
          wenkaitc.variable
        )}
      >
        {children}
        {sideBar}
      </ThemeProvider>
    </html>
  );
}
