import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/components/Providers/theme-provider";
import { cn } from "@/libs/utils";
import React from "react";

const geistSans = localFont({
  src: "../libs/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const rowdies = localFont({
  src: "../libs/fonts/Rowdies-Bold.ttf",
  variable: "--font-rowdies",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sideBar
}: Readonly<{
  children: React.ReactNode;
  sideBar: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider className={cn("bg-background text-text min-h-screen grid grid-cols-[1fr_8rem]", geistSans.variable, rowdies.variable)}>
        {children}
        {sideBar}
      </ThemeProvider>
    </html>
  );
}
